### ISSUE TITLE
Resolve ModuleNotFoundError when using the sim-explorer CLI

### ISSUE THREAD

**Issue by ClaasRostock** [dnv-opensource/sim-explorer#6]
ModuleNotFoundError: No module named 'sim_explorer.case'; 'sim_explorer' is not a package

**Comment by eisDNV** [comment]
I that related to the same error as found by several other participants: "AssertionError: Unable to create execution from path. Please check if path is correct..." There it turned out that the PyPi version of sim-explorer lags behind the pip install version and therefore newest features where not included when installing from PyPi. We need to check that.

**Comment by ClaasRostock** [comment]
The particular issue solved in PR #7  was not related to the "from pypi or not from pypi" effect.  I installed sim_explorer directly from source, and the behaviour with respect to the issue solved here was same; no difference in between installing from pypi or building from source. It was a second issue on top.

**Comment by eisDNV** [comment]
For my own learning: what exactly was the bug and what needs to be remembered to allow the package name as cli name?

**Comment by ClaasRostock** [comment]
I explained the background in a comment directly in sim_explorer/cli/sim_explorer.py.  See changes here in [PR #7](https://github.com/dnv-opensource/sim-explorer/pull/7/files)

**Comment by eisDNV** [comment]
Thank you. i did not find that before.
